### ISSUE TITLE
Nominatim URL should be configurable

### ISSUE THREAD

**Issue by shaunco** [owsas/opensource#171]
The Nominatim URL should be configurable at runtime. It is currently hardcoded at:
https://github.com/owsas/opensource/blob/6b86900e3ccea33e855f4a34d97c185eef178068/packages/nominatim-js/src/nominatim-js.ts#L94

Simply making the above `public` would be sufficient.

**Comment by jcguarinpenaranda** [comment]
Hello @shaunco,

I created a new PR for this issue. Could you please take a look and confirm it's as you would expect?

**Comment by shaunco** [comment]
Passing per call via the ISearchParams looks good 👍

Thanks for the amazingly fast fix!

**Comment by jcguarinpenaranda** [comment]
Thanks man. I'll merge and publish!

**Comment by jcguarinpenaranda** [comment]
Ok it was just uploaded. Could you please give it some time to replicate and test the new version nominatim-js@1.0.9? Thank you.

**Comment by shaunco** [comment]
Tested. Works great!

Thanks again!

**Comment by jcguarinpenaranda** [comment]
It's a pleasure. Thank you for using the library.
Juan
