### ISSUE TITLE
Add Reverse Geocoding Support

### ISSUE THREAD

**Issue by vladimirmyshkovski** [owsas/opensource#22]
In your current implementation, as I understand it, reverse geocoding is not possible. I want to transmit longitude and latitude, and get the address.

**Comment by jcguarinpenaranda** [comment]
Hello @vladimirmyshkovski ,
Currently this is possible by passing the latitude and longitude, comma separated in the "q" parameter. For example:

 ```js
const response = await NominatimJS.search({ q: '48.8583701,2.2942077' });
```
